### ISSUE TITLE
Influxd config does not export durations properly

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#2144]
When running `influxd config`, any field type of duration exports as an int, and is missing the unit of measure.

For example:

```toml
  retention-check-period = 600000000000
  retention-create-period = 2700000000000
```

Need to specify:

```go
type TextMarshaler interface {
        MarshalText() (text []byte, err error)
}
```

like:

```go
func (d *duration) MarshalText() (text []byte, err error) {
   ...
}
```
Here is a full export:

```toml
hostname = "Corys-MacBook-Pro.local"
bind-address = ""
reporting-disabled = false

[initialization]
  join-urls = ""

[authentication]
  enabled = false

[admin]
  enabled = true
  port = 8083

[api]
  port = 0
  ssl-port = 0
  ssl-cert = ""
  read-timeout = 0

[collectd]
  address = ""
  port = 0
  database = ""
  enabled = false
  typesdb = ""

[udp]
  enabled = false
  bind-address = ""
  port = 0

[broker]
  port = 8086
  dir = "/Users/corylanou/.influxdb/broker"
  election-timeout = 1000000000

[data]
  dir = "/Users/corylanou/.influxdb/data"
  port = 8086
  retention-auto-create = true
  retention-check-enabled = true
  retention-check-period = 600000000000
  retention-create-period = 2700000000000

[Snapshot]
  enabled = true
  bind-address = "127.0.0.1"
  port = 8087

[cluster]
  dir = ""

[logging]
  write-tracing = false
  raft-tracing = false

[Statistics]
  enabled = false
  database = "_internal"
  retention-policy = "default"
  write-interval = 60000000000

[continuous_queries]
  recompute-previous-n = 2
  recompute-no-older-than = 600000000000
  compute-runs-per-interval = 10
  compute-no-more-than = 120000000000
  disable = false
```
