### ISSUE TITLE
[0.8.x] Invalid data after new EC2 boots using EBS volume

### ISSUE THREAD

**Issue by DaveBlooman** [influxdb/influxdb#2744]
I have a single EC2 instance that has a EBS volume, on boot, the EBS volume attaches to the instance and my config file uses this volume for data storage.  After a new instance comes into service, the data doesn't restore correctly, all previous data before the EC2 deploy no longer represents the correct data.  

Here is a screenshot, the correct data is after 22:50, all the data before then is no longer correct but is stored on the EBS volume.  Is there anything that could be causing this, or something that is missing from my config.  I'm using version 0.8 on Centos 6 
![screenshot 2015-06-02 23 07 55](https://cloud.githubusercontent.com/assets/1492067/7948503/47273dec-097c-11e5-9844-4adaaf5afe54.png)

Here is my config

```toml

bind-address = "0.0.0.0"
reporting-disabled = true

[initialization]
join-urls = ""

[authentication]
enabled = false

[logging]
# logging level can be one of "fine", "debug", "info", "warn" or "error"
level  = "info"
file   = "/var/log/component/app.log"         # stdout to log to standard out, or syslog facility

# Configure the admin server
[admin]
port   = 8083              # binding is disabled if the port isn't set

# Configure the http api
[api]
port   = 8086    # binding is disabled if the node is not a Data node.
read-timeout = "5s"

[input_plugins]

  # Configure the graphite api
  [input_plugins.graphite]
  enabled = true
  port = 2003
  database = "graphite"  # store graphite data in this database
  # udp_enabled = true # enable udp interface on the same port as the tcp interface

  [input_plugins.collectd]
  enabled = true
  port = 25826
  database = "collectd"
  typesdb = "/usr/share/collectd/types.db"


# Raft configuration
[raft]
port = 8090 # Binding is disabled if node is not a Broker.
dir  = "/data/raft"
debug = false

[storage]

dir = "/data/db"
write-buffer-size = 10000
max-open-shards = 0
point-batch-size = 100
write-batch-size = 5000000
retention-sweep-period = "10m"

[cluster]

# Location for cluster state storage. For storing state persistently across restarts.
dir = "/data/state"

protobuf_port = 8099
protobuf_timeout = "2s" # the write timeout on the protobuf conn any duration parseable by time.ParseDuration
protobuf_heartbeat = "200ms" # the heartbeat interval between the servers. must be parseable by time.ParseDuration
protobuf_min_backoff = "1s" # the minimum backoff after a failed heartbeat attempt
protobuf_max_backoff = "10s" # the maxmimum backoff after a failed heartbeat attempt

write-buffer-size = 1000
max-response-buffer-size = 100

concurrent-shard-query-limit = 10

[leveldb]

max-open-files = 40

lru-cache-size = "200m"
max-open-shards = 0

point-batch-size = 100
write-batch-size = 5000000
[sharding]
replication-factor = 1

[sharding.short-term]
duration = "7d"
split = 1

[sharding.long-term]
duration = "30d"
split = 1
# split-random = "/^Hf.*/"

[wal]

dir   = "/data/wal"
flush-after = 1000 # the number of writes after which wal will be flushed, 0 for flushing on every write
bookmark-after = 1000 # the number of writes after which a bookmark will be created

# the number of writes after which an index entry is created pointing
# to the offset of the first request, default to 1k
index-after = 1000

# the number of requests per one log file, if new requests came in a
# new log file will be created
requests-per-logfile = 10000
```
